### ISSUE TITLE
Script only restores modified and accessed dates

### ISSUE THREAD

**Issue by 1024mb** [robertknight/mandrawer#1]
Hi, thanks to your script `save-file-attrs.py` I was able to save the dates of all my files which is very handy, now when I wanted to restore the dates it does it successfully but it doesn't restore the creation time nor for files nor folders, can you please look at it?

**Comment by robertknight** [comment]
The [os.utime](https://docs.python.org/3/library/os.html#os.utime) Python function I am using in the `save-file-attrs.py` script to restore times only supports setting the accessed and modified times. I don't know how to restore the creation time. Feel free to investigate and suggest a solution.

**Comment by 1024mb** [comment]
> 
> 
> The [os.utime](https://docs.python.org/3/library/os.html#os.utime) Python function I am using in the `save-file-attrs.py` script to restore times only supports setting the accessed and modified times. I don't know how to restore the creation time. Feel free to investigate and suggest a solution.

Thanks for the quick reply, I have been looking into it and I found some ways of restoring the creation times. See here: https://stackoverflow.com/a/56805533/10492351

I managed to restore the creation times with the answer I linked adding just a couple of lines but the module `win32_setctime` needs to be installed.
