### ISSUE TITLE
 save-file-attrs.py doesn't work on unicode-named folders

### ISSUE THREAD

**Issue by Owyn** [robertknight/mandrawer#2]
```
 line 20, in collect_file_attrs
    file_info = os.lstat(path)
WindowsError: [Error 123] ╤шэЄръёшўхёър  ю°шсър т шьхэш Їрщыр,: '.\\Nardack\\(C79) (??CG?) [Butterfly Dream (Nardack)] - Nardack artworks 2008-2010 (PNG)'
```

foldername is `(C79) (同人CG集) [Butterfly Dream (Nardack)] - Nardack artworks 2008-2010 (PNG)`

Windows 10 NTFS

**Comment by Owyn** [comment]
problem for python 2 it seems

seems like python2 was hiding somewhere in my system... cuz calling `python` was bringing forth python3

thx for the script btw, I think it might be one of a kind on the internet for its purpose for windows users 

I'll fork it to keep it save :-)

**Comment by robertknight** [comment]
> thx for the script btw, I think it might be one of a kind on the internet for its purpose for windows users

You're welcome. I haven't tested it with Windows myself so it is possible there are Windows-specific issues you might encounter. I have updated the script to explicitly use Python 3.
